name: nomabe
description: Nomabe an application that allows digital nomads to travel the world in a new, fast and simple way

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-378.0.dev <4.0.0'

dependencies:
  go_router: ^14.0.0
  get_it: ^7.6.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  graphql_flutter: ^5.1.2
  bloc_pattern: ^3.0.1
  rxdart: ^0.27.7
  bloc_test: ^9.1.4
  libphonenumber: ^2.0.2
  mask_text_input_formatter: ^2.5.0
  intl: ^0.19.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  dio: ^5.4.0
  injectable_generator: ^2.4.1
  injectable: ^2.3.2
  build_runner: ^2.4.8
  watcher: ^1.1.0
  google_generative_ai: ^0.3.1
  flutter_markdown: ^0.7.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.2
  network_image_mock: ^2.1.1
  injectable_generator: ^2.4.1
  flutter_dotenv: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/nomabe_logo.png
    - assets/.env
